import { useRef } from 'react'
import { RefreshCw, ExternalLink } from 'lucide-react'

export default function DriftFrame() {
  const iframeRef = useRef(null)

  const reload = () => {
    if (iframeRef.current) {
      iframeRef.current.src = iframeRef.current.src
    }
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-8 pt-8 pb-0">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-extrabold text-slate-100">Data Drift Report</h1>
            <p className="text-sm text-slate-500 mt-1">
              Interactive report generated by <span className="text-violet-400 font-medium">Evidently AI</span> — compares reference vs. current feature distributions
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={reload}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold
                         bg-white/[0.05] border border-white/[0.08] text-slate-400
                         hover:bg-white/[0.09] hover:text-slate-200 transition-all">
              <RefreshCw size={14} />
              Reload
            </button>
            <a href="/drift" target="_blank" rel="noreferrer"
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold
                         bg-white/[0.05] border border-white/[0.08] text-slate-400
                         hover:bg-white/[0.09] hover:text-slate-200 transition-all">
              <ExternalLink size={14} />
              Open
            </a>
          </div>
        </div>

        {/* Explainer cards */}
        <div className="mt-4 grid grid-cols-3 gap-3">
          {[
            { emoji: '📊', title: 'Feature Drift',   desc: 'Detects distribution shifts in each input feature' },
            { emoji: '🎯', title: 'Target Drift',    desc: 'Monitors changes in ad_clicked label distribution' },
            { emoji: '⚠️', title: 'Drift Alerts',   desc: 'Flags features with statistically significant drift' },
          ].map(({ emoji, title, desc }) => (
            <div key={title}
              className="p-4 rounded-xl bg-violet-500/[0.06] border border-violet-500/[0.15]">
              <p className="text-base mb-1">{emoji}</p>
              <p className="text-sm font-semibold text-slate-200">{title}</p>
              <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Iframe */}
      <div className="px-8 py-5 flex-1">
        <div className="w-full h-full rounded-2xl overflow-hidden border border-white/[0.08]
                        bg-slate-900 min-h-[500px]">
          <iframe
            ref={iframeRef}
            src="/drift"
            title="Evidently AI Data Drift Report"
            className="w-full h-full border-none"
            style={{ minHeight: 'calc(100vh - 280px)' }}
          />
        </div>
      </div>
    </div>
  )
}
