import { useRef } from 'react'
import { RefreshCw, ExternalLink } from 'lucide-react'

export default function MonitoringFrame() {
  const iframeRef = useRef(null)

  const reload = () => {
    if (iframeRef.current) {
      iframeRef.current.src = iframeRef.current.src
    }
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-8 pt-8 pb-0">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-extrabold text-slate-100">System Monitoring</h1>
            <p className="text-sm text-slate-500 mt-1">
              Live dashboard generated by the <code className="text-cyan-400 bg-cyan-500/10 px-1.5 py-0.5 rounded text-xs">mlops_monitoring</code> Airflow DAG · runs every 5 minutes
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={reload}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold
                         bg-white/[0.05] border border-white/[0.08] text-slate-400
                         hover:bg-white/[0.09] hover:text-slate-200 transition-all">
              <RefreshCw size={14} />
              Reload
            </button>
            <a href="/monitoring" target="_blank" rel="noreferrer"
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold
                         bg-white/[0.05] border border-white/[0.08] text-slate-400
                         hover:bg-white/[0.09] hover:text-slate-200 transition-all">
              <ExternalLink size={14} />
              Open
            </a>
          </div>
        </div>

        {/* Info strip */}
        <div className="mt-4 flex gap-3 flex-wrap">
          {[
            { emoji: '⚡', text: 'Redis health' },
            { emoji: '🗄️', text: 'MariaDB metrics' },
            { emoji: '📈', text: 'Evidently AI drift' },
            { emoji: '🤖', text: 'Model performance' },
          ].map(({ emoji, text }) => (
            <span key={text} className="flex items-center gap-1.5 text-xs text-slate-500
                                        bg-white/[0.04] border border-white/[0.07] px-2.5 py-1 rounded-full">
              {emoji} {text}
            </span>
          ))}
        </div>
      </div>

      {/* Iframe */}
      <div className="px-8 py-5 flex-1">
        <div className="w-full h-full rounded-2xl overflow-hidden border border-white/[0.08]
                        bg-slate-900 min-h-[500px]">
          <iframe
            ref={iframeRef}
            src="/monitoring"
            title="MLOps Monitoring Dashboard"
            className="w-full h-full border-none"
            style={{ minHeight: 'calc(100vh - 220px)' }}
          />
        </div>
      </div>
    </div>
  )
}
